### ISSUE TITLE
Ready for usage?

### ISSUE THREAD

**Issue by hansmbakker** [MakerDreams/grbl-Evo-One_v1.0#1]
@beegshot wonderful that you’re working on this grbl v1.1 firmware for our Kickstarter machines!

Is this code ready for use already? Could you please provide us with a guide on how to flash it on our evo-ones?

**Comment by beegshot** [comment]
Hi @wind-rider, yes, we are currently updating kickstarter machines with this firmware.
You can follow official grbl instructions here: https://github.com/gnea/grbl/wiki/Compiling-Grbl
(obviously you have to download this repo e not the "vanilla" one).

After the update you have to use the new cre-mov (Cre-Mov2018) software freely available here:
http://www.makerdreams.it/software-download-programmi/

Pay attention: while flashing with arduino IDE don't open the connection with the CNC mill with other software.

**Comment by hansmbakker** [comment]
Great to hear! I'd like to try it! I still have some questions:

- Is it possible to download the original firmware somewhere so that I can revert if something goes wrong?
- Are there any known issues?
- Could you please let me know what the current safety door behavior is? I saw that you worked on the safety door switch.
  - Can I still mill with an open safety door (to remove chips and dust while milling)?
  - Is [this issue](http://makerdreams.it/community/viewtopic.php?f=9&p=332&sid=3156d6f5f8e381dc17936841f4f95340#p331) solved?

**Comment by beegshot** [comment]
Yup!
Spindle:
Most of the work is about making grbl support brushless spindles in a proper way.
November modifications were not stable enough.
By the way we enhanced spindle step resolution :)

Door:
in the kickstarter machines we were using another type of switch (NO/NC) so firmware in this repo is configured accordingly.
I'm sorry but safety door behaviour in GRBL is not customizable (only enable/disable choice) so you cannot open the door while milling with this configuration.
Unfortunately original GRBL dev are not going to push updates anymore in their 328p repo and i doubt there are enough hardware resources to implment override feature **nicely**.

Old sources:
Let us few days to check and publish the old firmware.

**Comment by hansmbakker** [comment]
> only enable/disable choice

Am I right that I can disable it by commenting [line 175 in config.h](https://github.com/MakerDreams/grbl-Evo-One_v1.0/blob/ffc7cdc3cf945df6111047fcf6691eef893b9022/grbl/config.h#L175) so that I can keep the current Kickstarter firmware behavior?

I sometimes open the door while milling to remove dust / chips and i prefer not to interrupt the machine by opening the door.

**Comment by hansmbakker** [comment]
@andrea-pischedda @beegshot which board should we select for compiling / uploading in Arduino IDE? Am I right that I should select "Arduino/Genuino Uno"?

**Comment by hansmbakker** [comment]
@andrea-pischedda @beegshot I flashed this firmware on the kickstarter Evo-One and the homing X-direction is wrong! The spindle runs to the right-hand side where there is no limit switch!

Are you sure you uploaded all settings to this repository?

**Comment by hansmbakker** [comment]
It seems that the [direction mask](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#3--direction-port-invert-mask) is incorrect, could you please verify the line below for the X axis:
https://github.com/MakerDreams/grbl-Evo-One_v1.0/blob/ffc7cdc3cf945df6111047fcf6691eef893b9022/grbl/defaults.h#L473

I submitted #2; could you please verify that and merge it if it is correct so that others won't run into the same issue? Also I modified the setting in the EEPROM with `$3=3`.

**Comment by hansmbakker** [comment]
Could you please verify
https://github.com/MakerDreams/grbl-Evo-One_v1.0/blob/ffc7cdc3cf945df6111047fcf6691eef893b9022/grbl/defaults.h#L466

Having a maximum value for X of 389mm allows my spindle to run into the right-hand wall without stopping... This also risks causing damage to the spindle cable.

For my machine a safe value would be 380mm at most, and probably 374mm would be safer.

**Comment by hansmbakker** [comment]
@beegshot Can you please reopen this issue until this is fixed in master? Otherwise people might not see it and break their machine.

I can't reopen it myself.
